name: Tests - PyDev

on:
  push:
    branches:
      - master
      - pydev_9_3
  pull_request:
    branches:
      - master
      - pydev_9_3
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
          
      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7.18
          
      - name: Set up Python 2.7 deps
        run: |
            python2 -m pip install numpy django cython zope.interface
            
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.12
          
      - name: Set up Python 3.8 deps
        run: |
            python3 -m pip install PyQt5 cython
            
      - name: Set up Jython
        run: |
            curl https://repo1.maven.org/maven2/org/python/jython-installer/2.7.2/jython-installer-2.7.2.jar --output jython-installer.jar
            java -jar jython-installer.jar -s -d jython_install_dir
            
      - name: Print Python/Java info
        run: |
            pwd
            which python2
            python2 -c "import numpy;print(numpy.__file__)"
            python2 -c "import django;print(django.__file__)"
            python2 -c "import hmac;print(hmac.__file__)"
            python2 plugins/org.python.pydev.core/pysrc/interpreterInfo.py
            
            echo ---- 
            echo ----
            which python3
            echo SKIPPED python3 -c "import PyQt5;print(PyQt5.__file__)"
            python3 plugins/org.python.pydev.core/pysrc/interpreterInfo.py
            
            echo ---- 
            echo ----
            which java
            which mvn
            echo ---- rt.jar should be listed below
            find /opt/hostedtoolcache/Java_Adopt_jdk/11.0.11-9/x64/ -name "*.jar"
            
      - name: xvfb
        shell: bash
        env:
          DISPLAY: ":99.0"
        run: |
          sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX

        
      - name: Build with Maven
        run: mvn install -DskipTests=true

      - name: Add tests to plugin
        run: python3 builders/org.python.pydev.build/add_tests_to_plugins.py
        
      - name: Test with Maven
        env: 
            # We set the PYDEV_TEST_PLATFORM to control which TestDependent we use (i.e. TestDependent.github.properties)
            PYDEV_TEST_PLATFORM: github
            DISPLAY: ":99.0"
        run: mvn integration-test --batch-mode
